pluginManagement {
    repositories {
        // 镜像仓库 (国内加速，优先读取)
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url "https://maven-central-asia.storage-download.googleapis.com/maven2/" }

        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // 镜像仓库 (国内加速，优先读取)
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url "https://maven-central-asia.storage-download.googleapis.com/maven2/" }

        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        maven {
            url = 'https://jitpack.io'
            content {
                includeGroupByRegex("com\\.github.*")
            }
        }
        mavenCentral()
    }
}
rootProject.name = 'legado'

include ':app'
include ':modules:book'
include ':modules:rhino'